name: Create releases
on:
    push:
        tags:
            - v*
jobs:
    build:
        runs-on: ubuntu-latest
        container: registry.gitlab.com/josm/docker-library/openjdk-8-josmplugin:latest
        steps:
            - uses: actions/checkout@v2.3.4
            - run: ./gradlew dist
            - name: Release to GitHub
              id: release_to_github
              uses: actions/create-release@v1.1.4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false
            - name: Add file to release
              id: add_file_to_release
              uses: actions/upload-release-asset@v1.0.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.release_to_github.outputs.upload_url }}
                  asset_path: ./build/dist/pt_assistant.jar
                  asset_name: pt_assistant.jar
                  asset_content_type: application/java-archive
